version: "3.8"

services:
  artemis:
    image: quay.io/artemiscloud/activemq-artemis-broker:1.0.25
    container_name: artemis
    restart: unless-stopped
    ports:
      - "8161:8161"
      - "61616:61616"
      - "5672:5672"
    environment:
      - AMQ_USER=quarkus
      - AMQ_PASSWORD=quarkus
    networks:
      - parking_network

  parking-mongo:
    image: mongo:4.0.4
    container_name: parking-mongo
    restart: on-failure
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./data/parking:/data/db
    networks:
      - parking_network

  payments-mongo:
    image: mongo:4.0.4
    container_name: payments-mongo
    restart: on-failure
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./data/payments:/data/db
    networks:
      - parking_network

  parking-service:
    image: perkzen/parking-app-parking-service
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_MONGODB_CONNECTION_STRING=mongodb://root:root@parking-mongo:27017
      - QUARKUS_MONGODB_DATABASE=parking
      - QUARKUS_ARTEMIS_URL=tcp://artemis:61616
      - QUARKUS_ARTEMIS_USERNAME=quarkus
      - QUARKUS_ARTEMIS_PASSWORD=quarkus
    depends_on:
      - artemis
      - parking-mongo
    networks:
      - parking_network

  payments-service:
    image: perkzen/parking-app-payments-service
    ports:
      - "8081:8080"
      - "9000:9000"
    environment:
      - QUARKUS_MONGODB_CONNECTION_STRING=mongodb://root:root@payments-mongo:27017
    depends_on:
      - payments-mongo
    networks:
      - parking_network

  cars-db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: parking_app_db
    networks:
      - parking_network

  cars-service:
    image: perkzen/parking-app-cars-service
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://cars-db:5432/parking_app_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: true
      SPRINGDOC_SWAGGER_UI_PATH: /docs
    depends_on:
      - cars-db
    networks:
        - parking_network

  mobile-api-gateway:
    image: perkzen/parking-app-mobile-api-gateway
    ports:
      - "8083:8080"
    environment:
      - CAR_SERVICE_URL=http://cars-service:8080/api
      - PAYMENT_SERVICE_GRPC_URL=payments-service:9000
      - PAYMENT_SERVICE_URL=http://payments-service:8081
    networks:
      - parking_network
    depends_on:
      - cars-service
      - payments-service

  web-api-gateway:
    image: perkzen/parking-app-web-api-gateway
    ports:
      - "8084:8080"
    environment:
      - PARKING_SERVICE_URL=http://parking-service:8080
      - PAYMENT_SERVICE_GRPC_URL=payments-service:9000
      - PAYMENT_SERVICE_URL=http://payments-service:8081
    depends_on:
      - parking-service
      - payments-service
    networks:
      - parking_network

networks:
  parking_network:
    driver: bridge
